### PR TITLE
metadata mutation via wasm smart contracts support

### PR DESCRIPTION
**Pull request by ktalley-figure**
## Description

This PR adds metadata mutation support for Smart Contracts. It uses the `WriteScopeRequest` which contains the `Scope` type on the core side, and the respective type in provwasm for the Smart Contracts. All fields within the Scope type are available for modification following the current rules and restrictions.

closes: #531 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by iramiller** [comment]
@ktalley-figure looks like we need to have record writing and the other pieces added as well? I only see the scope (top most level) object supported here.

**Comment by iramiller** [comment]
> looks like we need to have record writing and the other pieces added as well?
Turns out that was all that was requested for the initial implementation ... in light of that I feel like it makes sense to merge in this for 1.8.0 as a great starting point with further integration coming in later revisions.

**Review by arnabmitra — APPROVED** [review]
lgtm

**Review by channa-figure — APPROVED** [review]
lgtm

**Review by iramiller — APPROVED** [review]

**Pull request merged**
