### PR TITLE
Add documentation for testing a software upgrade

### PR DESCRIPTION
**Pull request by fkneeland-figure**
## Description

In this pr I added a script and some documentation to make testing upgrades locally easier.

closes: #609 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by dwedul-figure — COMMENTED** [review]
Couple nits:

1. The level 3 headers should be level 2 (since there aren't any level 2 headers). `###` -> `##`
1. There should be stronger clarification that this is a procedure for testing and not for actually doing a software upgrade on a node. E.g. add `_testing` to the filename, add "Testing" to the title, and tweak the first purpose sentence to "This document outlines how to test a software upgrade locally."

**Comment by fkneeland-figure** [comment]
Thanks @dwedul-figure!  The pr has been updated accordingly

**Comment by iramiller** [comment]
What is `tutorial.wasm`?

**Comment by channa-figure** [comment]
When viewing the md file.  The ordered step numbers do not appear.  Just the check boxes.

**Review by dwedul-figure — APPROVED** [review]
LGTM

**Review by channa-figure — DISMISSED** [review]
LGTM

**Review by iramiller — APPROVED** [review]

**Review by channa-figure — APPROVED** [review]
LGTM

**Pull request merged**
