### PR TITLE
Feature/name migrate

### PR DESCRIPTION
**Pull request by arnabmitra**
## Description

closes: #99

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by dpederson-figure — APPROVED** [review]
LGTM

**Review by iramiller — APPROVED** [review]
👍🏻 

(should have a changelog entry though)

**Comment by arnabmitra** [comment]
> 👍🏻
> 
> (should have a changelog entry though)

added changelog entry

**Comment by arnabmitra** [comment]
Added changelog, hence needs a re-review @dpederson-figure @iramiller

**Review by dpederson-figure — APPROVED** [review]

**Pull request merged**
