### PR TITLE
Updated dependencies for M1

### PR DESCRIPTION
**Pull request by iramiller**
## Description

Updated `wasmd` to be the latest version available.

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by channa-figure — CHANGES_REQUESTED** [review]
Doesn't this need a change log entry?

**Comment by iramiller** [comment]
> Doesn't this need a change log entry?

We don't generally get change log entries for all the dependabot updates... and this one I expect to revision a few more times (final 1.0? before we go to release too.

**Review by fkneeland-figure — APPROVED** [review]
lgtm!

**Comment by iramiller** [comment]
Final version of this will be in #742 which is on the required list for the next release. (re: changelog, etc) ... this version is more of a wip to allow people to checkout/build main locally on an M1...

**Pull request merged**
