### PR TITLE
Update swagger, third-party protos, and related scripts.

### PR DESCRIPTION
**Pull request by SpicyLemon**
## Description

This does the following:
1. Updates the scripts/actions used to check and download the third party protos.
2. Updates the third party proto files.
3. Updates the swagger files.

closes: #1017 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by iramiller** [comment]
I am mostly ignoring the changes in this PR and focusing on the scripts ... when I run this locally I see some Proto formatting changes flagged ... have you pulled this all down and re-ran/committed the results recently?

**Comment by SpicyLemon** [comment]
> I am mostly ignoring the changes in this PR and focusing on the scripts ... when I run this locally I see some Proto formatting changes flagged ... have you pulled this all down and re-ran/committed the results recently?

Yup. You're right. The script that does the checking first compares `go.mod` between this branch and the target branch looking for differences. If there aren't any in the packages with protos we care about, it doesn't actually do any checking. There must have been changes to `go.mod` between when I originally ran this update and what ended up in `main` from the big branch.

I've temporarily added the `FORCE=1` env var to the github action so that it fails as expected.

Now, I'll do the following:
1. Snag a link to the now failed proto check run and add it as a comment on this ticket (for easy reference).
2. Make some tweaks to the script for more helpful output when skipping the check.
3. Update the third party protos.
4. Push those changes up.
5. Snag a link to the passed proto check (running with `FORCE=1`) and add it as a comment on this ticket.
6. Remove the `FORCE=1` from the github actions.

**Comment by SpicyLemon** [comment]
The failed check (with `FORCE=1` set): https://github.com/provenance-io/provenance/actions/runs/3099971549/jobs/5019731291

**Comment by SpicyLemon** [comment]
Alright. All fixed.

It was several formatting changes and the addition of the `ABCIResponsesInfo` message to `tendermint/state/types.proto`.

**Review by iramiller — APPROVED** [review]

**Pull request merged**
