### PR TITLE
Updated table driven unit tests to use named fields. 

### PR DESCRIPTION
**Pull request by shivenducs1136**
## Successfully added the required fields 

closes: #1436

- This PR have added field names to the required table driven unit test cases. 
- This is a draft PR while we make sure this meets use cases and needs.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by nullpointer0x00 — CHANGES_REQUESTED** [review]
Mostly looks good.  However, some tests are failing.  Run `make test` and resolve the ones that failed (https://github.com/provenance-io/provenance/actions/runs/4521605892).

**Comment by shivenducs1136** [comment]
Hi there, just fixed those failing test cases. thanks for guidance :)

**Comment by nullpointer0x00** [comment]
@shivenducs1136 almost there.  I'm still getting a few failures when running `make test` on your branch:
```
# github.com/provenance-io/provenance/x/marker/types
x/marker/types/msg_test.go:107:4: expected operand, found 'package'
FAIL	github.com/provenance-io/provenance/x/marker/types [setup failed]
# github.com/provenance-io/provenance/x/metadata/keeper
x/metadata/keeper/specification_test.go:1107:9: missing ',' in argument list
FAIL	github.com/provenance-io/provenance/x/metadata/keeper [setup failed]
ok  	github.com/provenance-io/provenance/app	2.848s
?   	github.com/provenance-io/provenance/app/params	[no test files]
?   	github.com/provenance-io/provenance/client/docs/statik	[no test files]
?   	github.com/provenance-io/provenance/cmd/dbmigrate	[no test files]
?   	github.com/provenance-io/provenance/cmd/dbmigrate/cmd	[no test files]
ok  	github.com/provenance-io/provenance/cmd/dbmigrate/utils	0.621s
?   	github.com/provenance-io/provenance/cmd/provenanced	[no test files]
# github.com/provenance-io/provenance/x/metadata/client/cli_test [github.com/provenance-io/provenance/x/metadata/client/cli.test]
x/metadata/client/cli/cli_test.go:2905:33: mixture of field:value and value elements in struct literal
x/metadata/client/cli/cli_test.go:2919:33: mixture of field:value and value elements in struct literal
ok  	github.com/provenance-io/provenance/cmd/provenanced/cmd	21.014s
ok  	github.com/provenance-io/provenance/cmd/provenanced/config	0.618s
ok  	github.com/provenance-io/provenance/internal/antewrapper	0.600s
ok  	github.com/provenance-io/provenance/internal/handlers	53.977s
ok  	github.com/provenance-io/provenance/internal/pioconfig	0.349s
?   	github.com/provenance-io/provenance/internal/provwasm	[no test files]
?   	github.com/provenance-io/provenance/internal/statesync	[no test files]
?   	github.com/provenance-io/provenance/testutil	[no test files]
ok  	github.com/provenance-io/provenance/x/attribute	0.939s
ok  	github.com/provenance-io/provenance/x/attribute/client/cli	44.180s
ok  	github.com/provenance-io/provenance/x/attribute/client/rest	19.738s
ok  	github.com/provenance-io/provenance/x/attribute/keeper	1.774s
ok  	github.com/provenance-io/provenance/x/attribute/simulation	3.137s
ok  	github.com/provenance-io/provenance/x/attribute/types	0.517s
?   	github.com/provenance-io/provenance/x/attribute/wasm	[no test files]
ok  	github.com/provenance-io/provenance/x/marker	3.527s
ok  	github.com/provenance-io/provenance/x/marker/client/cli	72.703s
ok  	github.com/provenance-io/provenance/x/marker/keeper	1.605s
ok  	github.com/provenance-io/provenance/x/marker/simulation	8.742s
?   	github.com/provenance-io/provenance/x/marker/wasm	[no test files]
ok  	github.com/provenance-io/provenance/x/metadata	0.607s
FAIL	github.com/provenance-io/provenance/x/metadata/client/cli [build failed]
```

**Comment by egaxhaj** [comment]
@shivenducs1136 Please don't make Pull Requests from a `main` branch. Create a new branch from an up to date `main` with `upstream` and PR that branch. Otherwise, you'll submit duplicate files in subsequent PRs as you have in #1445 (this should only contain changes to proto.yml).

**Comment by SpicyLemon** [comment]
Due to all the conflicts, and the age of this PR, I'm going to close it. Feel free to update the branch and re-open it though.

**Pull request closed without merging**
