### PR TITLE
Fix versioning in binary, docker, and others; to reference new VERISON string in makefile.

### PR DESCRIPTION
**Pull request by mtps**
## Description

Fix the versioning in docker and native binaries.
Build docker image using same make target as native binaries to ensure version args get passed in to `go build`.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by dpederson-figure — APPROVED** [review]

**Review by iramiller — DISMISSED** [review]
other than `Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c make VERSION=${VERSION} install]: exit code: 2` ... seems good to me

**Comment by mtps** [comment]
> other than `Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c make VERSION=${VERSION} install]: exit code: 2` ... seems good to me

LOL I'm looking into it.

**Comment by mtps** [comment]
Wasm doesn't support arm arch yet (supposedly support is coming as of 1.0+)

**Comment by iramiller** [comment]
> Wasm doesn't support arm arch yet (supposedly support is coming as of 1.0+)

Too bad for @dcshock and his magical never-needs-charging-doesnt-break-a-sweat laptop.

**Review by iramiller — APPROVED** [review]

**Comment by mtps** [comment]
@iramiller this includes all the build flags from the `make install` version (netgo, cleveldb, etc). Is there any unintended side effects this could have that I'm not catching?

**Comment by iramiller** [comment]
> any unintended side effects this could have that I'm not catching?

The only one I focus on really is getting the `cleveldb` flag set... I am not aware of any other major ones... the added version/commit params in 4.0.x gaia builds seem to be more about helpful information for running releases than anything else.

**Comment by mtps** [comment]
Seems they do a similar thing as we are doing
```
...
# Add source files
COPY . .

RUN go version

# Install minimum necessary dependencies, build Cosmos SDK, remove packages
RUN apk add --no-cache $PACKAGES && \
    make install
...
```

**Pull request merged**
