### PR TITLE
CLI Metadata querying functionality

### PR DESCRIPTION
**Pull request by dwedul-figure**
## Description

Add several queries to the Metadata CLI utility:
1.  `get id` - gets a metadata entry by a metadata address id.
1. `scope {scope_id|scope_uuid|session_id|record_id}` - gets a scope by either its metadata address id, a scope uuid, or the scope uuid contained in a session or record metadata address.
1. fullscope {scope_id|scope_uuid|session_id|record_id} - gets a scope, its sessions and its records by its metadata address id, a scope uuid, or the scope uuid contained in a session or record metadata address.
1. `session {session_id|scope_id|scope_uuid [session_uuid]}` - Gets a session by either its metadata address id or both its scope uuid and session uuid. Or gets all sessions associated with a scope id or scope uuid.
1. `record {record_id|session_id|scope_id|scope_uuid [record_name]}` - Gets a record by either its metadata address id or both its scope uuid and record name. Or gets all records associated with a session id or associated with a scope id or scope uuid.
1. `scopespec {scope_spec_id|scope_spec_uuid}` - Gets a scope specification by either its metadata address id or its uuid.
1. `contractspec {contract_spec_id|contract_spec_uuid|record_spec_id}` - Gets a contract specification by its metadata address id, or its uuid, or the contract spec uuid in a record spec id.
1. `recordspec {rec_spec_id|contract_spec_id|contract_spec_uuid [record_name]}` - Gets a record specification by either its metadata address id or its contract specification uuid and record specification name. Or gets all record specifications associated with a contract spec id or contract spec uuid.
1. `owner {address}` - Gets the scope uuids of scopes owned by this address.
1. `valueowner {address}` - Gets the scope uuids of scopes that have this address as the value owner.

closes: #142

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by iramiller — COMMENTED** [review]
Other than a question for @dpederson-figure on the conventions used for address conversion methods that panic on error ... I think this PR looks great.

**Comment by dpederson-figure** [comment]
> Other than a question for @dpederson-figure on the conventions used for address conversion methods that panic on error ... I think this PR looks great.

If it panics on the CLI or genesis, not a big deal.  Panics in modules *usually* aren't great (except in special cases).

**Review by dpederson-figure — DISMISSED** [review]
LGTM

**Review by iramiller — APPROVED** [review]
LGTM

**Pull request merged**
