### PR TITLE
Feature/named types

### PR DESCRIPTION
**Pull request by arnabmitra**
## Description

Typed Events and Metric counters in Name Module #85

closes: #85

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by arnabmitra** [comment]
this does break backwards compatibility for event names 
```
/ before name of the event was `types.EventTypeNameBound` == name_bound
	// because proto message format's do not encourage _ like convention
	// but prefer CamelCase for message name, NameBound
	// https://developers.google.com/protocol-buffers/docs/style
	// Use CamelCase (with an initial capital) for message names – for example, SongServerRequest.
	// Use underscore_separated_names for field names (including oneof field and extension names) – for example, song_name.
	// Emit event and return
	// Sample event:
	// [{"events":[{"type":"message","attributes":[{"key":"action","value":"bind_name"},{"key":"sender","value":"tp13ulywwfe7v38y0vetsqayccsgzexh6zq38h3d4"}]},{"type":"provenance.name.v1.EventNameBound","attributes":[{"key":"address","value":"\"tp13ulywwfe7v38y0vetsqayccsgzexh6zq38h3d4\""},{"key":"name","value":"\"sc1.pb\""}]},{"type":"transfer","attributes":[{"key":"recipient","value":"tp17xpfvakm2amg962yls6f84z3kell8c5l2udfyt"},{"key":"sender","value":"tp13ulywwfe7v38y0vetsqayccsgzexh6zq38h3d4"},{"key":"amount","value":"2000nhash"}]}]}]
```

**Comment by arnabmitra** [comment]
Did add handler_test.go which test's out emission of events.

**Review by channa-figure — APPROVED** [review]
LGTM.  I will follow the same test structure in marker module for confirming the event.

**Review by channa-figure — CHANGES_REQUESTED** [review]
Sorry, for approving then requesting changes.  I notice when I checked out your branch and ran the go formatter it made some changes.  Are you running that after saves?

**Comment by arnabmitra** [comment]
> Sorry, for approving then requesting changes. I notice when I checked out your branch and ran the go formatter it made some changes. Are you running that after saves?

good question, when i started i noticed `golangci-lint run --fix` would fix gofmt error's on the linter, and assumed it runs gofmt if not run..
 what do you  guys run? i can follow the same convention

**Comment by channa-figure** [comment]
@arnabmitra I know we talked about this in private, but I will post it publicly here.  

I don't run the gofmt command-line through all the files right now (it would muddy up the PR too much IMO).  My editors `emacs` and `vscode` do it for me on save for the files I'm editing.  Maybe we should have a PR to format all the files and then add some enforcement to PR's?

**Review by channa-figure — APPROVED** [review]
LGTM.  Thanks!

**Comment by arnabmitra** [comment]
> @arnabmitra I know we talked about this in private, but I will post it publicly here.
> 
> I don't run the gofmt command-line through all the files right now (it would muddy up the PR too much IMO). My editors `emacs` and `vscode` do it for me on save for the files I'm editing. Maybe we should have a PR to format all the files and then add some enforcement to PR's?

i think the linter check does check the fmt.. for e.g if you check in a badly formatted file ..like add several tabs..it will complain..when i did my first PR i had a bunch of gofmt errors in the linter..

**Pull request merged**
