### PR TITLE
Add context field to sessions.

### PR DESCRIPTION
**Pull request by dwedul-figure**
## Description

Add a `context` field to the `Session` message.

Also add a `write-session` CLI command and standardize the `Use` lines for the metadata tx CLI commands based on the cobra documentation.

closes: #276 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by piercetrey-figure** [comment]
@dwedul-figure I think we will need a way to set this context on the `MsgP8eMemorializeContractRequest` and have that be set on the session via the conversion

**Comment by dwedul-figure** [comment]
> @dwedul-figure I think we will need a way to set this context on the `MsgP8eMemorializeContractRequest` and have that be set on the session via the conversion

Doh! Yup. Totally forgot that part. Fixed now though. I added it to the `Contract` message: `MsgP8eMemorializeContractRequest.Contract.Context`. It's an `Any` field there too, and it just gets straight up copied over into the `Session.Context` field.

**Review by iramiller — DISMISSED** [review]
One thing to potentially look for is a validation function for that proto any type url ... there are restrictions on the values that are allowed in there per spec... but I wouldn't try to write your own if there isn't one easily usable within the protobuf SDK.

**Comment by iramiller** [comment]
> A URL/resource name that uniquely identifies the type of the serialized
> protocol buffer message. This string must contain at least
> one "/" character. The last segment of the URL's path must represent
> the fully qualified name of the type (as in
> `path/google.protobuf.Duration`). The name should be in a canonical form
> (e.g., leading "." is not accepted).
> 
> In practice, teams usually precompile into the binary all types that they
> expect it to use in the context of Any. However, for URLs which use the
> scheme `http`, `https`, or no scheme, one can optionally set up a type
> server that maps type URLs to message definitions as follows:
> 
> * If no scheme is provided, `https` is assumed.
> * An HTTP GET on the URL must yield a [google.protobuf.Type][]
> 	value in binary format, or produce an error.
> * Applications are allowed to cache lookup results based on the
> 	URL, or have them precompiled into a binary to avoid any
> 	lookup. Therefore, binary compatibility needs to be preserved
> 	on changes to types. (Use versioned type names to manage
> 	breaking changes.)
> 
> Note: this functionality is not currently available in the official
> protobuf release, and it is not used for type URLs beginning with
> type.googleapis.com.
> 
> Schemes other than `http`, `https` (or the empty scheme) might be
> used with implementation specific semantics.

**Comment by piercetrey-figure** [comment]
I think I am running into issues when sending an Any value related to the stuff @iramiller mentioned above. I have tried several different ways (different prefixes, setting the any type url to `github.com/provenance-io/provenance/x/metadata/types/p8e.UUID` thinking maybe I had to use the go_package version) and seem to always get something like `UNKNOWN: unable to resolve type URL /provenance.metadata.v1.p8e.UUID: tx parse error: invalid request`.

Initially I was using a proto from within p8e, but hten switched to this UUID proto that is present in the provenance p8e protos, hoping that it would resolve, but no luck so far.

**Comment by dwedul-figure** [comment]
Note for the future: The Cosmos SDK was trying to do some automatic validation of the `Any` field and failing because it couldn't find the `TypeURL`s being provided. So we decided to just use a byte array for the `Context` instead. Since the `Session` already is already associated with a process, it shouldn't have to tell others what the `Context` is.

**Review by channa-figure — APPROVED** [review]
LGTM, I like the edits to the cobra commands.

**Pull request merged**
