### PR TITLE
enable adr 038 state listening

### PR DESCRIPTION
**Pull request by egaxhaj-figure**
## Description

Enable State Listening plugin system.

closes: #785 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by derekadams — DISMISSED** [review]

**Comment by iramiller** [comment]
When this is ready it needs to go into main as well as this 1.8.x branch...

**Comment by egaxhaj-figure** [comment]
> When this is ready it needs to go into main as well as this 1.8.x branch...

This is good to go now. Will be able to merge into main once the upstream work is merged in `cosmos/master`

**Review by channa-figure — DISMISSED** [review]

**Comment by dwedul-figure** [comment]
Okay. I merged main into this branch and ironed out the conflicts. PR #732 went into `release/v1.8.x` but never into `main`. So this PR now also contains that stuff too. I also updated the changelog to reflect v1.8.1.

**Review by dwedul-figure — APPROVED** [review]

**Review by iramiller — APPROVED** [review]
This looks like a clean patch to me.

**Review by derekadams — APPROVED** [review]

**Pull request merged**
