### PR TITLE
Add validation on the session's contract spec id with respects to the scope's scope spec.

### PR DESCRIPTION
**Pull request by dwedul-figure**
## Description

When writing a session, ensure that the scope spec of the scope allows the contract spec of the session.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by iramiller** [comment]
This is a breaking change... we need to get a certification from @scirner22 and @piercetrey-figure that they expect it to work this way... Also we probably shouldn't put this in 1.3.x

**Comment by piercetrey-figure** [comment]
We are setting the contract spec ids on the scope spec when bootstrapping, so I think this should work. We can pull this branch down and test it out as well. @scirner22 do you concur?

**Comment by scirner22** [comment]
> We are setting the contract spec ids on the scope spec when bootstrapping, so I think this should work. We can pull this branch down and test it out as well. @scirner22 do you concur?

This sounds accurate. When this is out of draft we can test it locally just to verify.

**Comment by dwedul-figure** [comment]
This is now ready for review.

**Review by channa-figure — APPROVED** [review]
Nice, LGTM!

**Review by arnabmitra — DISMISSED** [review]

**Review by arnabmitra — APPROVED** [review]

**Pull request merged**
