### PR TITLE
Update third party proto files

### PR DESCRIPTION
**Pull request by fkneeland-figure**
## Summary

As part of updating to 0.43 of the Cosmos SDK the third party proto definitions also should be reviewed and updated as needed

## Problem Definition

The third party proto files are stored in the provenance repository as canonical versions for build dependencies.  These files are managed using a `make proto-update-deps` target.  The referenced sources must be updated when the SDK is updated.

## Proposal

- [ ] Review the target sources for the third party proto files and update as required to versions that match the 0.43 Cosmos SDK.  
- [ ] Execute the target and commit resulting proto files.

closes: #391 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by fkneeland-figure** [comment]
@iramiller It looks like none of the versions for the third party protos changed in cosmos 0.43.  So I just updated the makefile to get cosmos protos from 0.43 and ran the make script.

https://github.com/provenance-io/provenance/blob/main/Makefile#L409
https://github.com/cosmos/cosmos-sdk/blob/master/Makefile#L416

Is there anywhere else that I should check on that?

**Review by iramiller — APPROVED** [review]
LGTM.  With no *.go file changes the extra PR GHA checks won't run

**Comment by fkneeland-figure** [comment]
@iramiller are you able to merge this pr?  I can only set for it to auto merge, but as you said the checks won't all finish as there are no go code changes.

**Comment by iramiller** [comment]
Yes I will take care of it.

**Pull request merged**
